
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 18 04:20:55 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRATEGY_BEGIN = 2;
  public static final int CHAR = 11;
  public static final int EXECUTED_BY = 25;
  public static final int DOUBLE = 8;
  public static final int GREATER = 19;
  public static final int REPEAT = 12;
  public static final int INT = 7;
  public static final int REDEPLOY_ON = 29;
  public static final int LESS = 17;
  public static final int STRINGCONST = 38;
  public static final int CLOSE_CURLY_BRACKET = 16;
  public static final int SEMICOLON = 6;
  public static final int INTCONST = 34;
  public static final int BOOL = 10;
  public static final int DOUBLECONST = 35;
  public static final int PLUS = 31;
  public static final int MULTIPLY = 32;
  public static final int ASSIGN = 20;
  public static final int IF = 26;
  public static final int ID = 33;
  public static final int EOF = 0;
  public static final int EQUAL = 18;
  public static final int error = 1;
  public static final int CLOSE_BRACKET = 14;
  public static final int OPEN_BRACKET = 13;
  public static final int SERVICE_NAME = 24;
  public static final int NUM_INSTANCES = 21;
  public static final int SCALE = 28;
  public static final int CHARCONST = 37;
  public static final int OPEN_CURLY_BRACKET = 15;
  public static final int DECLARATION_BEGIN = 4;
  public static final int THEN = 27;
  public static final int BOOLCONST = 36;
  public static final int OPTIMIZE = 30;
  public static final int STRING = 9;
  public static final int DECLARATION_END = 5;
  public static final int SERVICE_END = 23;
  public static final int SERVICE_BEGIN = 22;
  public static final int STRATEGY_END = 3;
}

