
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 18 21:09:06 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COLON = 6;
  public static final int STRINGCONST = 2;
  public static final int EOF = 0;
  public static final int REALCONST = 4;
  public static final int ID = 9;
  public static final int error = 1;
  public static final int COMMA = 5;
  public static final int OPENCURLY = 7;
  public static final int INTCONST = 3;
  public static final int CLOSECURLY = 8;
}

