
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jan 19 13:09:36 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ENUM = 2;
  public static final int INT = 6;
  public static final int COLON = 3;
  public static final int STRINGCONST = 10;
  public static final int EOF = 0;
  public static final int STRING = 7;
  public static final int ID = 11;
  public static final int COMMA = 8;
  public static final int error = 1;
  public static final int OPENCURLY = 4;
  public static final int INTCONST = 9;
  public static final int CLOSECURLY = 5;
}

