
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 18 21:08:57 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPENPAR = 6;
  public static final int COLON = 5;
  public static final int STRINGCONST = 3;
  public static final int CLOSEPAR = 7;
  public static final int EOF = 0;
  public static final int ID = 8;
  public static final int error = 1;
  public static final int COMMA = 4;
  public static final int INTCONST = 2;
}

