
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Dec 16 01:43:00 CET 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CLOSE_BRACKET = 15;
  public static final int MULTIPLY = 34;
  public static final int SERVICE_END = 25;
  public static final int SEMICOLON = 7;
  public static final int PLUS = 33;
  public static final int DECLARATION_BEGIN = 4;
  public static final int INT = 8;
  public static final int THEN = 29;
  public static final int EQUAL = 20;
  public static final int CHAR = 12;
  public static final int DECLARATION_END = 5;
  public static final int GREATER = 21;
  public static final int IF = 28;
  public static final int STRATEGY_END = 3;
  public static final int ID = 6;
  public static final int OPEN_BRACKET = 14;
  public static final int STRING = 10;
  public static final int OPTIMIZE = 32;
  public static final int CLOSE_CURLY_BRACKET = 17;
  public static final int SCALE = 30;
  public static final int SERVICE_BEGIN = 24;
  public static final int EOF = 0;
  public static final int REDEPLOY_ON = 31;
  public static final int SERVICE_NAME = 26;
  public static final int CONST = 18;
  public static final int error = 1;
  public static final int ASSIGN = 22;
  public static final int EXECUTED_BY = 27;
  public static final int BOOL = 11;
  public static final int OPEN_CURLY_BRACKET = 16;
  public static final int NUM_INSTANCES = 23;
  public static final int REPEAT = 13;
  public static final int STRATEGY_BEGIN = 2;
  public static final int LESS = 19;
  public static final int DOUBLE = 9;
}

