
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 18 21:04:58 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRINGCONST = 4;
  public static final int EOF = 0;
  public static final int REALCONST = 5;
  public static final int ID = 2;
  public static final int ASSIGN = 8;
  public static final int POINTER = 7;
  public static final int error = 1;
  public static final int COMMA = 6;
  public static final int INTCONST = 3;
}

