
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu May 15 11:17:33 CEST 2008
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 8;
  public static final int ELSE = 12;
  public static final int PLUS = 13;
  public static final int THEN = 11;
  public static final int SEMI = 19;
  public static final int CHAR = 5;
  public static final int LEFTPAR = 15;
  public static final int END = 7;
  public static final int INTCONST = 23;
  public static final int RIGHTPAR = 16;
  public static final int IF = 10;
  public static final int ID = 22;
  public static final int WRITE = 9;
  public static final int PROGRAM = 2;
  public static final int BEGIN = 6;
  public static final int COMMA = 20;
  public static final int EOF = 0;
  public static final int CHARCONST = 24;
  public static final int DOTDOT = 17;
  public static final int DOT = 21;
  public static final int error = 1;
  public static final int ASSIGN = 18;
  public static final int INTEGER = 4;
  public static final int MUL = 14;
  public static final int VAR = 3;
}

